services:
  kodus-service-billing:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - log_volume:/app/logs
    logging:
      options:
        max-size: "200m"
        max-file: "10"
    ports:
      - "3992:3992"
    environment:
      - ENV=homolog
    env_file:
      - .env.qa
    restart: unless-stopped

volumes:
  log_volume:
